### ISSUE TITLE
Improve the `test_setup` script in Makefile to prevent accidental deletion

### ISSUE THREAD

**Issue by siddhant-deepsource** [DeepSourceCorp/cli#181]
The `test_setup` recipe in Makefile has a step: `cd ${CODE_PATH} && ls -A1 | xargs rm -rf` which can accidently delete some significant directories if `CODE_PATH` is not configured.

**Comment by akshaya-hub** [comment]
i think to prevent this issue it is recommended to either set the CODE_PATH environment variable to a safe value before running the test_setup recipe, or to modify the recipe so that it only deletes specific files or directories that are not needed for the test. Additionally, you may want to add a check in the recipe to ensure that the CODE_PATH environment variable is set to a non-empty value before proceeding with the deletion step.

**Comment by vishnu-deepsource** [comment]
We should add unit tests.  Closing this in favour of https://github.com/DeepSourceCorp/cli/issues/241
